### Imports

In [1]:
import torch
import networks
import datasetLoader
import importlib

importlib.reload(datasetLoader)
importlib.reload(networks)


<module 'networks' from 'c:\\Users\\trist\\Git_repos\\BT-ML-PGESAT\\code\\PGExplainer\\networks.py'>

### Testing PyG

In [ ]:
from torch_geometric.data import Data

edge_index = torch.tensor([[0, 1, 1, 2],
                           [1, 0, 2, 1]], dtype=torch.long)
x = torch.tensor([[-1], [0], [1]], dtype=torch.float)

data = Data(x=x, edge_index=edge_index)
print(data)

### Parameters

In [57]:
learning_rate_gnn = 0.001        #0.001 on ADAM
epochs_graphgnn = 5000
epochs_nodegnn = 1000


learning_rate_mlp = 0.003        #0.003 on ADAM
coefficientSizeReg = 0.05
entropyReg = 1
epochs_mlp = 30

temperature =  0        #???


In [ ]:
#gnn_optimizer = torch.optim.Adam(lr = learning_rate_gnn)
#mlp_optimizer = torch.optim.Adam(lr = learning_rate_mlp)

train_loader, test_laoder = datasetLoader.loadDataset('BA2Motif', 1)               # TODO: adjs matrix is not compatible with GraphConv. Needs to be converted to edge_index (see RE_PGE datasets/utils)

gnn = networks.GraphGNN(features= 10, output_dim= 1)
# gnn.forward(feas, adjs.nonzero().t().contiguous())



"""for i in enumerate(adjs):
    #out = gnn.forward(feas[i], adjs[i].nonzero().t().contiguous())

for epoch in epochs_graphgnn:
    for graph in adjs:
        # calculate latent variables? MLP?
        for k in # k in monte carlo sampling?!
            # sammple graph
            # pred label on sampled graph

    # compute loss
    # update params with backprop"""

    

'for i in enumerate(adjs):\n    #out = gnn.forward(feas[i], adjs[i].nonzero().t().contiguous())\n\nfor epoch in epochs_graphgnn:\n    for graph in adjs:\n        # calculate latent variables? MLP?\n        for k in # k in monte carlo sampling?!\n            # sammple graph\n            # pred label on sampled graph\n\n    # compute loss\n    # update params with backprop'

In [3]:
print(next(iter(train_loader)))         # edge_index = "map" for edges, x = features, y = node classes; labels missing, 
print(next(iter(train_loader)).y)
print(next(iter(train_loader)).x)
#train_features, train_labels = next(iter(dataLoader))
#print(train_features)
#print(train_labels)

curr = next(iter(train_loader))

out = gnn.forward(curr.x, curr.edge_index, None)

DataBatch(x=[25, 10], edge_index=[2, 52], y=[1], batch=[25], ptr=[2])
tensor([0])
tensor([[0.1000, 0.1000, 0.1000, 0.1000, 0.1000, 0.1000, 0.1000, 0.1000, 0.1000,
         0.1000],
        [0.1000, 0.1000, 0.1000, 0.1000, 0.1000, 0.1000, 0.1000, 0.1000, 0.1000,
         0.1000],
        [0.1000, 0.1000, 0.1000, 0.1000, 0.1000, 0.1000, 0.1000, 0.1000, 0.1000,
         0.1000],
        [0.1000, 0.1000, 0.1000, 0.1000, 0.1000, 0.1000, 0.1000, 0.1000, 0.1000,
         0.1000],
        [0.1000, 0.1000, 0.1000, 0.1000, 0.1000, 0.1000, 0.1000, 0.1000, 0.1000,
         0.1000],
        [0.1000, 0.1000, 0.1000, 0.1000, 0.1000, 0.1000, 0.1000, 0.1000, 0.1000,
         0.1000],
        [0.1000, 0.1000, 0.1000, 0.1000, 0.1000, 0.1000, 0.1000, 0.1000, 0.1000,
         0.1000],
        [0.1000, 0.1000, 0.1000, 0.1000, 0.1000, 0.1000, 0.1000, 0.1000, 0.1000,
         0.1000],
        [0.1000, 0.1000, 0.1000, 0.1000, 0.1000, 0.1000, 0.1000, 0.1000, 0.1000,
         0.1000],
        [0.1000, 0.1000, 0.

RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x40 and 20x2)

## Testing

In [ ]:
print(labels.shape[0])
print(adjs[999])
print(feas[0])
print(labels[0])
print(feas[0].shape[0])

In [34]:
from torch_geometric.datasets import ExplainerDataset
from torch_geometric.datasets.graph_generator import BAGraph
from torch_geometric.datasets.motif_generator import HouseMotif
from torch_geometric.datasets.motif_generator import CycleMotif
import torch_geometric.transforms as T
from torch_geometric.loader import DataLoader

dataset1 = ExplainerDataset(
            graph_generator=BAGraph(20, 1),
            motif_generator=HouseMotif(),
            num_motifs=1,
            num_graphs=400,
            transform=T.Constant()      # appends value 1 node feature for every node
        )

dataset2 = ExplainerDataset(
            graph_generator=BAGraph(20, 1),
            motif_generator=CycleMotif(5),
            num_motifs=1,
            num_graphs=400,
            transform=T.Constant()
        )

dataset = torch.utils.data.ConcatDataset([dataset1, dataset2])

print(dataset)
dataset[0].y = torch.tensor([0])

print(dataset[0].y)

train_loader = DataLoader(dataset1, batch_size = 1, shuffle = True)

print(next(iter(train_loader)).y)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 2, 2,
        3])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 2, 2,
        3])
